python MTRec.py --arch-sparse-feature-size=64 \
					--arch-mlp-bot="13-512-256-64" \
					--arch-mlp-top="512-512-256-1" \
					--arch-interaction-op=transformers \
					--num-encoder-layers=1 \
					--num-attention-heads=2 \
					--feedforward-dim=512 \
					--norm-first=False \
					--activation=relu \
					--mask-threshold=0.001-0.005-0.01-0.05 \
					--data-generation=dataset \
					--data-set=<dataset_name> \
					--raw-data-file=<path_to_raw_dataset> \
					--processed-data-file=<path_to_processed_dataset> \
					--loss-function=<loss_fucntion> \
					--round-targets=True \
					--learning-rate=0.1 \
					--mini-batch-size=128 \
					--print-freq=1024 \
					--print-time \
					--test-mini-batch-size=4096 \
					--test-num-workers=16 \
					--test-freq=1024 \
					--nepochs=5 \
					--mlperf-logging