python ../../Non_Seq_Rec_Model/MTRec.py --arch-sparse-feature-size=16 \
					--arch-mlp-bot="13-512-256-64-16" \
					--arch-mlp-top="512-256-1" \
					--arch-interaction-op=transformers \
					--num-encoder-layers=1 \
					--num-attention-heads=2 \
					--feedforward-dim=128 \
					--dropout=0.01 \
					--norm-first=False \
					--activation=relu \
					--mask-threshold=0.001-0.005-0.01-0.05 \
					--data-generation=dataset \
					--data-set=kaggle \
					--raw-data-file=<path_to_raw_dataset> \
					--processed-data-file=<path_to_processed_dataset> \
					--loss-function=<loss_fucntion> \
					--round-targets=True \
					--learning-rate=0.1 \
					--mini-batch-size=128 \
					--print-freq=4096 \
					--print-time \
					--test-mini-batch-size=16384 \
					--test-num-workers=12 \
					--test-freq=4096 \
					--nepochs=5 \
					--mlperf-logging \
					--numpy-rand-seed=123 \
					--mlperf-auc-threshold=0.80